In [1]:
import numpy as np
array = np.arange(0, 25)
matrix = array.reshape((5, 5))
# Manually rotate the matrix counterclockwise
rotated_matrix = np.zeros((5,5))
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        rotated_matrix[j, matrix.shape[0] - 1 - i] = matrix[i, j]
# Flip the matrix vertically
flipped_matrix = np.flip(rotated_matrix, axis=0)
# Extracting the center 3x3 part of the flipped matrix using sclicing
region = flipped_matrix[1:4, 1:4]

In [2]:
rotated_matrix_1

array([[20., 15., 10.,  5.,  0.],
       [21., 16., 11.,  6.,  1.],
       [22., 17., 12.,  7.,  2.],
       [23., 18., 13.,  8.,  3.],
       [24., 19., 14.,  9.,  4.]])

In [ ]:
# 1.
# Rotate the image 90 degrees clockwise. (DO NOT use np.rot90 or any built-in rotation functions)
# 2.
# Flip the rotated image horizontally.
# 3.
# Crop out the center 100x100 pixels of the previously rotated and flipped.

In [7]:
# 1번
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        rotated_matrix[matrix.shape[0] - 1 - i,j] = matrix[i,j]
k = []
for i in range(5):
    k.append(np.sort(rotated_matrix[i])[::-1])
rotated_matrix_2 = np.array(k)
rotated_matrix_2

array([[24., 23., 22., 21., 20.],
       [19., 18., 17., 16., 15.],
       [14., 13., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [4]:
# 1번
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        rotated_matrix[j,matrix.shape[0] - 1 - i] = matrix[i,j]
k = []
for i in range(5):
    k.append(np.sort(rotated_matrix[i])[::-1])
rotated_matrix_3 = np.array(k)
rotated_matrix_3

array([[20., 15., 10.,  5.,  0.],
       [21., 16., 11.,  6.,  1.],
       [22., 17., 12.,  7.,  2.],
       [23., 18., 13.,  8.,  3.],
       [24., 19., 14.,  9.,  4.]])

In [8]:
# 2번
flipped_matrix = np.flip(rotated_matrix_2, axis=1)
flipped_matrix

array([[20., 21., 22., 23., 24.],
       [15., 16., 17., 18., 19.],
       [10., 11., 12., 13., 14.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [ ]:
# 3번
flipped_matrix = flipped_matrix[0:100, 0:100, ]
flipped_matrix